# Generated by Django 4.0.4 on 2022-05-16 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_shopuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 10, 33, 57, 358771)),
        ),
    ]
