# Generated by Django 4.0.4 on 2022-05-17 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_users_shopuserprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 23, 32, 295224)),
        ),
    ]
